// Admin API behind the web UI.
//
// Two rules shape everything here:
//   1. Provider keys go out to the browser masked, never in full. The UI can
//      prove a key exists and delete it; it can never read it back.
//   2. The access key is generated by FreeChain and is meant to be copied into
//      other apps, so that one is returned in full on request.

import crypto from 'node:crypto';
import path from 'node:path';
import { PROVIDERS, FAMILIES, ACCOUNT_SLOTS, MAX_KEYS_PER_ACCOUNT, envBaseFor } from './providers.js';
import { resolveKeys, resolveAccounts, chainStatus, saveChainConfig, ROOT } from './config.js';
import { setEnvVars, reloadEnv } from './envfile.js';

export const ENV_FILE = process.env.FREECHAIN_ENV_FILE || path.join(ROOT, '.env');

// Not FREECHAIN_LOCAL_API_KEY — that name already belongs to the `local`
// provider slot, and the collision would make the two overwrite each other.
export const ACCESS_KEY_VAR = 'FREECHAIN_ACCESS_KEY';

// Where to send a user who needs a key for this provider. Feeds the "Get a
// key" / site buttons on the Model sources page automatically for every
// provider here. The sidebar's static quick-link list (webui/index.html) only
// covers providers actually in the default chain, so add an entry there too
// when a new provider earns a permanent spot in chain.config.json.
export const PROVIDER_LINKS = {
  openrouter: { site: 'https://openrouter.ai/', keys: 'https://openrouter.ai/keys' },
  'opencode-zen': { site: 'https://opencode.ai/zen', keys: 'https://opencode.ai/zen' },
  omniroute: { site: 'https://omniroute.online/', keys: 'https://omniroute.online/' },
  longcat: { site: 'https://longcat.chat/', keys: 'https://longcat.chat/' },
  groq: { site: 'https://groq.com/', keys: 'https://console.groq.com/keys' },
  cerebras: { site: 'https://cerebras.ai/', keys: 'https://cloud.cerebras.ai/' },
  nvidia: { site: 'https://build.nvidia.com/', keys: 'https://build.nvidia.com/' },
  deepseek: { site: 'https://deepseek.com/', keys: 'https://platform.deepseek.com/api_keys' },
  google: { site: 'https://ai.google.dev/', keys: 'https://aistudio.google.com/apikey' },
  openai: { site: 'https://openai.com/', keys: 'https://platform.openai.com/api-keys' },
  local: { site: 'https://ollama.com/', keys: null },
};

/** Enough to identify a key without revealing it. */
export function maskKey(key) {
  if (!key) return '';
  if (key.length <= 10) return `${key.slice(0, 2)}${'•'.repeat(6)}`;
  return `${key.slice(0, 5)}${'•'.repeat(6)}${key.slice(-4)}`;
}

export function getAccessKey() {
  return process.env[ACCESS_KEY_VAR]?.trim() || null;
}

/** Create the access key on first run so the UI always has one to show. */
export function ensureAccessKey() {
  const existing = getAccessKey();
  if (existing) return existing;
  const key = `fc-${crypto.randomBytes(24).toString('base64url')}`;
  setEnvVars(ENV_FILE, { [ACCESS_KEY_VAR]: key });
  process.env[ACCESS_KEY_VAR] = key;
  return key;
}

export function rotateAccessKey() {
  const key = `fc-${crypto.randomBytes(24).toString('base64url')}`;
  setEnvVars(ENV_FILE, { [ACCESS_KEY_VAR]: key });
  process.env[ACCESS_KEY_VAR] = key;
  return key;
}

/**
 * Constant-time compare so a wrong key cannot be discovered by timing.
 * Lengths are compared first because timingSafeEqual throws on a mismatch.
 */
export function accessKeyMatches(presented) {
  const expected = getAccessKey();
  if (!expected) return true; // no key configured yet: do not lock the user out
  if (!presented) return false;
  const a = Buffer.from(presented);
  const b = Buffer.from(expected);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

export function bearerFrom(req) {
  const h = req.headers.authorization || '';
  return h.startsWith('Bearer ') ? h.slice(7).trim() : h.trim() || null;
}

/** Full provider inventory for the UI: slots, masked keys, links, chain use. */
export function inventory(chain) {
  const usedFamilies = new Set(
    chain.links.map((l) => PROVIDERS[l.provider]?.family).filter(Boolean)
  );

  const providers = FAMILIES.map((family) => {
    const def = PROVIDERS[family];
    const slots = [family, ...Array.from({ length: ACCOUNT_SLOTS }, (_, n) => `${family}${n}`)].map(
      (id) => ({
        id,
        label: id === family ? 'default' : `slot ${id.slice(family.length)}`,
        envVar: envBaseFor(id),
        keys: resolveKeys(id).map((k, i) => ({ index: i, masked: maskKey(k) })),
      })
    );
    return {
      family,
      label: def.label,
      baseUrl: def.baseUrl,
      keyOptional: Boolean(def.keyOptional),
      links: PROVIDER_LINKS[family] || {},
      inChain: usedFamilies.has(family),
      modelCount: chain.links.filter((l) => PROVIDERS[l.provider]?.family === family).length,
      totalKeys: slots.reduce((n, s) => n + s.keys.length, 0),
      activeSlots: slots.filter((s) => s.keys.length).length,
      slots,
    };
  });

  const status = chainStatus(chain);
  return {
    providers,
    chain: chain.links.map((l, i) => ({ ...status[i], baseUrl: l.baseUrl, note: l.note })),
    limits: { accountSlots: ACCOUNT_SLOTS, keysPerSlot: MAX_KEYS_PER_ACCOUNT },
    totals: {
      links: chain.links.length,
      ready: status.filter((s) => s.hasKey).length,
      candidates: chain.links.reduce(
        (n, l) => n + (resolveAccounts(l.provider).length || (l.keyOptional ? 1 : 0)),
        0
      ),
    },
  };
}

// The UI only ever sees masked keys, so it cannot resend an existing one. It
// sends "keep:<index>" instead, which is resolved here against what is already
// stored. Anything else is treated as a new key.
const KEEP = /^keep:(\d+)$/;

/** Replace one slot's keys. An empty list clears the slot. */
export function saveSlotKeys(slotId, keys) {
  if (!PROVIDERS[slotId]) throw new Error(`Unknown provider slot "${slotId}"`);
  const existing = resolveKeys(slotId);

  const resolved = keys.map((raw) => {
    const value = String(raw).trim();
    const keep = KEEP.exec(value);
    if (!keep) return value;
    const kept = existing[Number(keep[1])];
    if (kept === undefined) throw new Error(`Cannot keep key #${keep[1]}: it no longer exists`);
    return kept;
  });

  const clean = [...new Set(resolved.filter(Boolean))].slice(0, MAX_KEYS_PER_ACCOUNT);
  const base = envBaseFor(slotId);

  // Clear every form this slot could have been written in, so the singular and
  // numbered variants cannot resurrect a key the user just deleted.
  const updates = { [base]: null, [`${base}S`]: clean.length ? clean.join(',') : null };
  for (let n = 1; n <= MAX_KEYS_PER_ACCOUNT; n++) updates[`${base}_${n}`] = null;

  setEnvVars(ENV_FILE, updates);
  for (const name of Object.keys(updates)) delete process.env[name];
  reloadEnv(ENV_FILE);
  return clean.length;
}

export function reorderChain(chain, order) {
  if (!Array.isArray(order) || order.length !== chain.links.length) {
    throw new Error(`order must be an array of ${chain.links.length} indices`);
  }
  const seen = new Set();
  for (const idx of order) {
    if (typeof idx !== 'number' || idx < 0 || idx >= chain.links.length || seen.has(idx)) {
      throw new Error(`invalid or duplicate index: ${idx}`);
    }
    seen.add(idx);
  }
  chain.links = order.map((idx, pos) => {
    const link = chain.links[idx];
    return { ...link, index: pos };
  });
  saveChainConfig(chain);
}

/** Live check: does this slot actually answer for one of the chain's models? */
export async function testSlot(chain, slotId, timeoutMs = 20_000) {
  const def = PROVIDERS[slotId];
  if (!def) throw new Error(`Unknown provider slot "${slotId}"`);

  const link = chain.links.find((l) => PROVIDERS[l.provider]?.family === def.family);
  if (!link) return { ok: false, reason: `No chain entry uses ${def.family}` };

  const [key] = resolveKeys(slotId);
  if (!key && !def.keyOptional) return { ok: false, reason: 'No key configured for this slot' };

  const started = Date.now();
  try {
    const res = await fetch(`${link.baseUrl}/chat/completions`, {
      method: 'POST',
      signal: AbortSignal.timeout(timeoutMs),
      headers: {
        'Content-Type': 'application/json',
        ...(key ? { Authorization: `Bearer ${key}` } : {}),
        ...(def.headers || {}),
      },
      body: JSON.stringify({
        model: link.model,
        max_tokens: 1,
        messages: [{ role: 'user', content: 'ping' }],
      }),
    });
    const ms = Date.now() - started;
    if (res.ok) return { ok: true, ms, model: link.model };
    const detail = (await res.text().catch(() => '')).slice(0, 200);
    return { ok: false, ms, status: res.status, model: link.model, reason: detail || `HTTP ${res.status}` };
  } catch (err) {
    return { ok: false, ms: Date.now() - started, reason: err.message };
  }
}
